### ISSUE TITLE
FR: Add timeout option

### ISSUE THREAD

**Issue by ScottPierce** [kgit2/kommand#10]
It'd be nice if I could add a timeout to a command that if it didn't finish by a certain time, the child process was killed.

**Comment by BppleMan** [comment]
I need to refer to more APIs for child processes in other languages to provide a more elegant solution, which will involve the use of asynchronous/coroutine, and may not be friendly to asynchronous novices.
This is good advice but it will take some time

**Comment by BppleMan** [comment]
As I said, cancelable tasks rely on asynchronous scheduling. 

The cancellation of asynchronous tasks relies on suspension, and the mechanism behind it is thread scheduling.

Cancellation of a thread simply discards the thread handle.

The subprocess is different from a thread or coroutine. But a process is indeed a task that can be canceled.

Therefore, in version 2.0, I added a `kill` method to the `Command`, so that we can rely on the asynchronous packaging of `kotlinx-coroutines` to turn it into a timeout and cancelable task.

Therefore, I announce that this feature has been implemented. For details, please see the readme [timeout] topic.

**Comment by ScottPierce** [comment]
Sounds good to me
